stop fail2ban before running puppet
this is a workaround after the latest firewall changes

d69a781fa235bb4e2554635e43a7e9488f16067b
7eabc74cbfeb0c04e49aba2f81678b8a60b4442b
7f9f93cc5240e8ec5e41be31c5b078bcc29ff87f

this changed made puppet to cleanup chains and rules before stopping
fail2ban

```
Notice: Compiled catalog for dn42-md-1.4679.ar in environment production in 2.16 seconds
Notice: /Stage[main]/Profile::Networking::Firewall/Firewall[9025 967cf342dd7503442cfa99190b221049]/ensure: removed
Notice: /Stage[main]/Profile::Networking::Firewall/Firewall[9026 065c47f845b7c353d6a29ceecdc8befd]/ensure: removed
Notice: /Stage[main]/Profile::Networking::Firewall/Firewall[9027 3585002fe487161b55201a5e338a7c0f]/ensure: removed
Notice: /Stage[main]/Profile::Networking::Firewall/Firewall[9028 d298b979d58c8e76dbecb93f37ed05d3]/ensure: removed
Notice: /Stage[main]/Profile::Networking::Firewall/Firewallchain[f2b-sshd:filter:IPv4]/ensure: removed
Notice: /Stage[main]/Profile::Networking::Firewall::Pre/Exec[stop_fail2ban]/returns: executed successfully
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: executed successfully
```

which makes fail2ban to crash when it is stopped and tries to remove the
rules

```
Dec 07 04:09:26 dn42-md-1 fail2ban.utils[3278651]: ERROR 7fc8782c2a80 -- exec: iptables -w -F f2b-sshd
Dec 07 04:09:26 dn42-md-1 fail2ban.utils[3278651]: ERROR 7fc8782c2a80 -- stderr: 'iptables: No chain/target/match by that name.'
Dec 07 04:09:26 dn42-md-1 fail2ban.utils[3278651]: ERROR 7fc8782c2a80 -- returned 1
Dec 07 04:09:26 dn42-md-1 fail2ban.actions[3278651]: ERROR Failed to flush bans in jail 'sshd' action 'iptables-multiport': Error flushing action Jail('sshd')/iptables-multiport: 'Script error'
Dec 07 04:09:26 dn42-md-1 fail2ban.actions[3278651]: INFO No flush occurred, do consistency check
Dec 07 04:09:26 dn42-md-1 fail2ban.utils[3278651]: ERROR 7fc8782b72d0 -- exec: iptables -w -n -L FILTERS | grep -q 'f2b-sshd[ \t]'
Dec 07 04:09:26 dn42-md-1 fail2ban.utils[3278651]: ERROR 7fc8782b72d0 -- returned 1
Dec 07 04:09:26 dn42-md-1 fail2ban[3278651]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 653, in __flushBan
if action.flush():
File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 637, in flush
return self._executeOperation('<actionflush>', 'flushing', family=family, afterExec=_afterFlush)
File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 476, in _executeOperation
raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))
RuntimeError: Error flushing action Jail('sshd')/iptables-multiport: 'Script error'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/fail2ban/server/jailthread.py", line 69, in run_with_except_hook
run(*args, **kwargs)
File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 368, in run
self.__flushBan(stop=True)
File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 666, in __flushBan
action.consistencyCheck(_beforeRepair)
File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 690, in consistencyCheck
if started and not self._invariantCheck(family, beforeRepair):
File "/usr/lib/python3/dist-packages/fail2ban/server/action.py", line 916, in _invariantCheck
if beforeRepair and not beforeRepair():
File "/usr/lib/python3/dist-packages/fail2ban/server/actions.py", line 663, in _beforeRepair
self._logSys.error("Invariant check failed. Flush is impossible.")
AttributeError: 'Actions' object has no attribute '_logSys'
```

until puppet is fixed, just stop fail2ban before calling puppet

[skip ci]